# Generated by Django 5.2.6 on 2025-09-20 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
        ("tenants", "0002_tenant_is_active_tenant_is_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                    ("manager", "Manager"),
                    ("owner", "Owner"),
                ],
                default="owner",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="tenant",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
