# Generated by Django 5.2.6 on 2025-09-21 11:15

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_is_active_tenant_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                default="demo",
                max_length=63,
                unique=True,
                validators=[django_tenants.postgresql_backend.base._check_schema_name],
            ),
            preserve_default=False,
        ),
    ]
